# Generated by Django 3.2.9 on 2023-05-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_device_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHCSR04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.IntegerField()),
                ('timestamp_origin', models.IntegerField()),
                ('timestamp_receive', models.IntegerField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
